//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Fotokiosk1
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Запись клиента.
    /// </summary>
    // *** Start programmer edit section *** (ЗаписьКлиента CustomAttributes)

    // *** End programmer edit section *** (ЗаписьКлиента CustomAttributes)
    [AutoAltered()]
    [Caption("Запись клиента")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗаписьКлиентаE", new string[] {
            "ДатаЗаписи as \'Дата записи\'",
            "ФамилияИмя as \'Фамилия имя\'",
            "Телефон as \'Телефон\'",
            "Сотрудники as \'Сотрудники\'",
            "Сотрудники.ФИО as \'ФИО\'"}, Hidden=new string[] {
            "Сотрудники.ФИО"})]
    [AssociatedDetailViewAttribute("ЗаписьКлиентаE", "Услуга", "УслугаE", true, "", "Услуга", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("ЗаписьКлиентаE", "Сотрудники", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [View("ЗаписьКлиентаL", new string[] {
            "ДатаЗаписи as \'Дата записи\'",
            "ФамилияИмя as \'Фамилия имя\'",
            "Телефон as \'Телефон\'",
            "Сотрудники.ФИО as \'ФИО\'"})]
    public class ЗаписьКлиента : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДатаЗаписи = System.DateTime.Now;
        
        private string fФамилияИмя;
        
        private string fТелефон;
        
        private IIS.Fotokiosk1.Сотрудники fСотрудники;
        
        private IIS.Fotokiosk1.DetailArrayOfУслуга fУслуга;
        
        // *** Start programmer edit section *** (ЗаписьКлиента CustomMembers)

        // *** End programmer edit section *** (ЗаписьКлиента CustomMembers)

        
        /// <summary>
        /// ДатаЗаписи.
        /// </summary>
        // *** Start programmer edit section *** (ЗаписьКлиента.ДатаЗаписи CustomAttributes)

        // *** End programmer edit section *** (ЗаписьКлиента.ДатаЗаписи CustomAttributes)
        public virtual System.DateTime ДатаЗаписи
        {
            get
            {
                // *** Start programmer edit section *** (ЗаписьКлиента.ДатаЗаписи Get start)

                // *** End programmer edit section *** (ЗаписьКлиента.ДатаЗаписи Get start)
                System.DateTime result = this.fДатаЗаписи;
                // *** Start programmer edit section *** (ЗаписьКлиента.ДатаЗаписи Get end)

                // *** End programmer edit section *** (ЗаписьКлиента.ДатаЗаписи Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаписьКлиента.ДатаЗаписи Set start)

                // *** End programmer edit section *** (ЗаписьКлиента.ДатаЗаписи Set start)
                this.fДатаЗаписи = value;
                // *** Start programmer edit section *** (ЗаписьКлиента.ДатаЗаписи Set end)

                // *** End programmer edit section *** (ЗаписьКлиента.ДатаЗаписи Set end)
            }
        }
        
        /// <summary>
        /// Телефон.
        /// </summary>
        // *** Start programmer edit section *** (ЗаписьКлиента.Телефон CustomAttributes)

        // *** End programmer edit section *** (ЗаписьКлиента.Телефон CustomAttributes)
        [StrLen(255)]
        public virtual string Телефон
        {
            get
            {
                // *** Start programmer edit section *** (ЗаписьКлиента.Телефон Get start)

                // *** End programmer edit section *** (ЗаписьКлиента.Телефон Get start)
                string result = this.fТелефон;
                // *** Start programmer edit section *** (ЗаписьКлиента.Телефон Get end)

                // *** End programmer edit section *** (ЗаписьКлиента.Телефон Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаписьКлиента.Телефон Set start)

                // *** End programmer edit section *** (ЗаписьКлиента.Телефон Set start)
                this.fТелефон = value;
                // *** Start programmer edit section *** (ЗаписьКлиента.Телефон Set end)

                // *** End programmer edit section *** (ЗаписьКлиента.Телефон Set end)
            }
        }
        
        /// <summary>
        /// ФамилияИмя.
        /// </summary>
        // *** Start programmer edit section *** (ЗаписьКлиента.ФамилияИмя CustomAttributes)

        // *** End programmer edit section *** (ЗаписьКлиента.ФамилияИмя CustomAttributes)
        [StrLen(255)]
        public virtual string ФамилияИмя
        {
            get
            {
                // *** Start programmer edit section *** (ЗаписьКлиента.ФамилияИмя Get start)

                // *** End programmer edit section *** (ЗаписьКлиента.ФамилияИмя Get start)
                string result = this.fФамилияИмя;
                // *** Start programmer edit section *** (ЗаписьКлиента.ФамилияИмя Get end)

                // *** End programmer edit section *** (ЗаписьКлиента.ФамилияИмя Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаписьКлиента.ФамилияИмя Set start)

                // *** End programmer edit section *** (ЗаписьКлиента.ФамилияИмя Set start)
                this.fФамилияИмя = value;
                // *** Start programmer edit section *** (ЗаписьКлиента.ФамилияИмя Set end)

                // *** End programmer edit section *** (ЗаписьКлиента.ФамилияИмя Set end)
            }
        }
        
        /// <summary>
        /// Запись клиента.
        /// </summary>
        // *** Start programmer edit section *** (ЗаписьКлиента.Сотрудники CustomAttributes)

        // *** End programmer edit section *** (ЗаписьКлиента.Сотрудники CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудники"})]
        [NotNull()]
        public virtual IIS.Fotokiosk1.Сотрудники Сотрудники
        {
            get
            {
                // *** Start programmer edit section *** (ЗаписьКлиента.Сотрудники Get start)

                // *** End programmer edit section *** (ЗаписьКлиента.Сотрудники Get start)
                IIS.Fotokiosk1.Сотрудники result = this.fСотрудники;
                // *** Start programmer edit section *** (ЗаписьКлиента.Сотрудники Get end)

                // *** End programmer edit section *** (ЗаписьКлиента.Сотрудники Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаписьКлиента.Сотрудники Set start)

                // *** End programmer edit section *** (ЗаписьКлиента.Сотрудники Set start)
                this.fСотрудники = value;
                // *** Start programmer edit section *** (ЗаписьКлиента.Сотрудники Set end)

                // *** End programmer edit section *** (ЗаписьКлиента.Сотрудники Set end)
            }
        }
        
        /// <summary>
        /// Запись клиента.
        /// </summary>
        // *** Start programmer edit section *** (ЗаписьКлиента.Услуга CustomAttributes)

        // *** End programmer edit section *** (ЗаписьКлиента.Услуга CustomAttributes)
        public virtual IIS.Fotokiosk1.DetailArrayOfУслуга Услуга
        {
            get
            {
                // *** Start programmer edit section *** (ЗаписьКлиента.Услуга Get start)

                // *** End programmer edit section *** (ЗаписьКлиента.Услуга Get start)
                if ((this.fУслуга == null))
                {
                    this.fУслуга = new IIS.Fotokiosk1.DetailArrayOfУслуга(this);
                }
                IIS.Fotokiosk1.DetailArrayOfУслуга result = this.fУслуга;
                // *** Start programmer edit section *** (ЗаписьКлиента.Услуга Get end)

                // *** End programmer edit section *** (ЗаписьКлиента.Услуга Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаписьКлиента.Услуга Set start)

                // *** End programmer edit section *** (ЗаписьКлиента.Услуга Set start)
                this.fУслуга = value;
                // *** Start programmer edit section *** (ЗаписьКлиента.Услуга Set end)

                // *** End programmer edit section *** (ЗаписьКлиента.Услуга Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗаписьКлиентаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаписьКлиентаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаписьКлиентаE", typeof(IIS.Fotokiosk1.ЗаписьКлиента));
                }
            }
            
            /// <summary>
            /// "ЗаписьКлиентаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаписьКлиентаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаписьКлиентаL", typeof(IIS.Fotokiosk1.ЗаписьКлиента));
                }
            }
        }
    }
}
