//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Fotokiosk1
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Материал.
    /// </summary>
    // *** Start programmer edit section *** (Материал CustomAttributes)

    // *** End programmer edit section *** (Материал CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("МатериалE", new string[] {
            "Код as \'Код\'",
            "Наименование as \'Наименование\'",
            "Марка as \'Марка\'"})]
    [View("МатериалL", new string[] {
            "Код as \'Код\'",
            "Наименование as \'Наименование\'",
            "Марка as \'Марка\'"})]
    public class Материал : ICSSoft.STORMNET.DataObject
    {
        
        private int fКод;
        
        private string fНаименование;
        
        private string fМарка;
        
        // *** Start programmer edit section *** (Материал CustomMembers)

        // *** End programmer edit section *** (Материал CustomMembers)

        
        /// <summary>
        /// Код.
        /// </summary>
        // *** Start programmer edit section *** (Материал.Код CustomAttributes)

        // *** End programmer edit section *** (Материал.Код CustomAttributes)
        public virtual int Код
        {
            get
            {
                // *** Start programmer edit section *** (Материал.Код Get start)

                // *** End programmer edit section *** (Материал.Код Get start)
                int result = this.fКод;
                // *** Start programmer edit section *** (Материал.Код Get end)

                // *** End programmer edit section *** (Материал.Код Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Материал.Код Set start)

                // *** End programmer edit section *** (Материал.Код Set start)
                this.fКод = value;
                // *** Start programmer edit section *** (Материал.Код Set end)

                // *** End programmer edit section *** (Материал.Код Set end)
            }
        }
        
        /// <summary>
        /// Марка.
        /// </summary>
        // *** Start programmer edit section *** (Материал.Марка CustomAttributes)

        // *** End programmer edit section *** (Материал.Марка CustomAttributes)
        [StrLen(255)]
        public virtual string Марка
        {
            get
            {
                // *** Start programmer edit section *** (Материал.Марка Get start)

                // *** End programmer edit section *** (Материал.Марка Get start)
                string result = this.fМарка;
                // *** Start programmer edit section *** (Материал.Марка Get end)

                // *** End programmer edit section *** (Материал.Марка Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Материал.Марка Set start)

                // *** End programmer edit section *** (Материал.Марка Set start)
                this.fМарка = value;
                // *** Start programmer edit section *** (Материал.Марка Set end)

                // *** End programmer edit section *** (Материал.Марка Set end)
            }
        }
        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (Материал.Наименование CustomAttributes)

        // *** End programmer edit section *** (Материал.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (Материал.Наименование Get start)

                // *** End programmer edit section *** (Материал.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (Материал.Наименование Get end)

                // *** End programmer edit section *** (Материал.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Материал.Наименование Set start)

                // *** End programmer edit section *** (Материал.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (Материал.Наименование Set end)

                // *** End programmer edit section *** (Материал.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "МатериалE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View МатериалE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("МатериалE", typeof(IIS.Fotokiosk1.Материал));
                }
            }
            
            /// <summary>
            /// "МатериалL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View МатериалL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("МатериалL", typeof(IIS.Fotokiosk1.Материал));
                }
            }
        }
    }
}
