//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Fotokiosk1
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Прайс.
    /// </summary>
    // *** Start programmer edit section *** (Прайс CustomAttributes)

    // *** End programmer edit section *** (Прайс CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПрайсE", new string[] {
            "Наименование as \'Наименование\'",
            "Цена as \'Цена\'"})]
    [View("ПрайсL", new string[] {
            "Наименование as \'Наименование\'",
            "Цена as \'Цена\'"})]
    public class Прайс : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаименование;
        
        private double fЦена;
        
        // *** Start programmer edit section *** (Прайс CustomMembers)

        // *** End programmer edit section *** (Прайс CustomMembers)

        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (Прайс.Наименование CustomAttributes)

        // *** End programmer edit section *** (Прайс.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (Прайс.Наименование Get start)

                // *** End programmer edit section *** (Прайс.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (Прайс.Наименование Get end)

                // *** End programmer edit section *** (Прайс.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Прайс.Наименование Set start)

                // *** End programmer edit section *** (Прайс.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (Прайс.Наименование Set end)

                // *** End programmer edit section *** (Прайс.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Цена.
        /// </summary>
        // *** Start programmer edit section *** (Прайс.Цена CustomAttributes)

        // *** End programmer edit section *** (Прайс.Цена CustomAttributes)
        public virtual double Цена
        {
            get
            {
                // *** Start programmer edit section *** (Прайс.Цена Get start)

                // *** End programmer edit section *** (Прайс.Цена Get start)
                double result = this.fЦена;
                // *** Start programmer edit section *** (Прайс.Цена Get end)

                // *** End programmer edit section *** (Прайс.Цена Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Прайс.Цена Set start)

                // *** End programmer edit section *** (Прайс.Цена Set start)
                this.fЦена = value;
                // *** Start programmer edit section *** (Прайс.Цена Set end)

                // *** End programmer edit section *** (Прайс.Цена Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПрайсE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПрайсE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПрайсE", typeof(IIS.Fotokiosk1.Прайс));
                }
            }
            
            /// <summary>
            /// "ПрайсL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПрайсL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПрайсL", typeof(IIS.Fotokiosk1.Прайс));
                }
            }
        }
    }
}
