//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Fotokiosk1
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Расход материала.
    /// </summary>
    // *** Start programmer edit section *** (РасходМатериала CustomAttributes)

    // *** End programmer edit section *** (РасходМатериала CustomAttributes)
    [AutoAltered()]
    [Caption("Расход материала")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("РасходМатериалаE", new string[] {
            "Материал as \'Материал\'",
            "Материал.Наименование as \'Наименование\'",
            "Количество as \'Количество\'",
            "Материал.Марка as \'Марка\'"}, Hidden=new string[] {
            "Материал.Наименование"})]
    [MasterViewDefineAttribute("РасходМатериалаE", "Материал", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    public class РасходМатериала : ICSSoft.STORMNET.DataObject
    {
        
        private int fКоличество;
        
        private IIS.Fotokiosk1.Материал fМатериал;
        
        private IIS.Fotokiosk1.Трудозатраты fТрудозатраты;
        
        // *** Start programmer edit section *** (РасходМатериала CustomMembers)

        // *** End programmer edit section *** (РасходМатериала CustomMembers)

        
        /// <summary>
        /// Количество.
        /// </summary>
        // *** Start programmer edit section *** (РасходМатериала.Количество CustomAttributes)

        // *** End programmer edit section *** (РасходМатериала.Количество CustomAttributes)
        public virtual int Количество
        {
            get
            {
                // *** Start programmer edit section *** (РасходМатериала.Количество Get start)

                // *** End programmer edit section *** (РасходМатериала.Количество Get start)
                int result = this.fКоличество;
                // *** Start programmer edit section *** (РасходМатериала.Количество Get end)

                // *** End programmer edit section *** (РасходМатериала.Количество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РасходМатериала.Количество Set start)

                // *** End programmer edit section *** (РасходМатериала.Количество Set start)
                this.fКоличество = value;
                // *** Start programmer edit section *** (РасходМатериала.Количество Set end)

                // *** End programmer edit section *** (РасходМатериала.Количество Set end)
            }
        }
        
        /// <summary>
        /// Расход материала.
        /// </summary>
        // *** Start programmer edit section *** (РасходМатериала.Материал CustomAttributes)

        // *** End programmer edit section *** (РасходМатериала.Материал CustomAttributes)
        [PropertyStorage(new string[] {
                "Материал"})]
        [NotNull()]
        public virtual IIS.Fotokiosk1.Материал Материал
        {
            get
            {
                // *** Start programmer edit section *** (РасходМатериала.Материал Get start)

                // *** End programmer edit section *** (РасходМатериала.Материал Get start)
                IIS.Fotokiosk1.Материал result = this.fМатериал;
                // *** Start programmer edit section *** (РасходМатериала.Материал Get end)

                // *** End programmer edit section *** (РасходМатериала.Материал Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РасходМатериала.Материал Set start)

                // *** End programmer edit section *** (РасходМатериала.Материал Set start)
                this.fМатериал = value;
                // *** Start programmer edit section *** (РасходМатериала.Материал Set end)

                // *** End programmer edit section *** (РасходМатериала.Материал Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Fotokiosk1.Трудозатраты.
        /// </summary>
        // *** Start programmer edit section *** (РасходМатериала.Трудозатраты CustomAttributes)

        // *** End programmer edit section *** (РасходМатериала.Трудозатраты CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Трудозатраты"})]
        public virtual IIS.Fotokiosk1.Трудозатраты Трудозатраты
        {
            get
            {
                // *** Start programmer edit section *** (РасходМатериала.Трудозатраты Get start)

                // *** End programmer edit section *** (РасходМатериала.Трудозатраты Get start)
                IIS.Fotokiosk1.Трудозатраты result = this.fТрудозатраты;
                // *** Start programmer edit section *** (РасходМатериала.Трудозатраты Get end)

                // *** End programmer edit section *** (РасходМатериала.Трудозатраты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РасходМатериала.Трудозатраты Set start)

                // *** End programmer edit section *** (РасходМатериала.Трудозатраты Set start)
                this.fТрудозатраты = value;
                // *** Start programmer edit section *** (РасходМатериала.Трудозатраты Set end)

                // *** End programmer edit section *** (РасходМатериала.Трудозатраты Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "РасходМатериалаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РасходМатериалаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РасходМатериалаE", typeof(IIS.Fotokiosk1.РасходМатериала));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of РасходМатериала.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfРасходМатериала CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfРасходМатериала CustomAttributes)
    public class DetailArrayOfРасходМатериала : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Fotokiosk1.DetailArrayOfРасходМатериала members)

        // *** End programmer edit section *** (IIS.Fotokiosk1.DetailArrayOfРасходМатериала members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type РасходМатериала by index.
        /// </summary>
        /// <summary>
        /// Adds object with type РасходМатериала.
        /// </summary>
        public DetailArrayOfРасходМатериала(IIS.Fotokiosk1.Трудозатраты fТрудозатраты) : 
                base(typeof(РасходМатериала), ((ICSSoft.STORMNET.DataObject)(fТрудозатраты)))
        {
        }
        
        public IIS.Fotokiosk1.РасходМатериала this[int index]
        {
            get
            {
                return ((IIS.Fotokiosk1.РасходМатериала)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Fotokiosk1.РасходМатериала dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
