//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Fotokiosk1
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Трудозатраты.
    /// </summary>
    // *** Start programmer edit section *** (Трудозатраты CustomAttributes)

    // *** End programmer edit section *** (Трудозатраты CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТрудозатратыE", new string[] {
            "ДатаОтчета as \'Дата отчета\'",
            "Сотрудники as \'Сотрудники\'",
            "Сотрудники.ФИО as \'ФИО\'",
            "Сотрудники.Должность as \'Должность\'"}, Hidden=new string[] {
            "Сотрудники.ФИО"})]
    [AssociatedDetailViewAttribute("ТрудозатратыE", "РасходМатериала", "РасходМатериалаE", true, "", "Расход материала", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("ТрудозатратыE", "Сотрудники", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [View("ТрудозатратыL", new string[] {
            "ДатаОтчета as \'Дата отчета\'",
            "Сотрудники.ФИО as \'ФИО\'"})]
    public class Трудозатраты : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДатаОтчета;
        
        private IIS.Fotokiosk1.Сотрудники fСотрудники;
        
        private IIS.Fotokiosk1.DetailArrayOfРасходМатериала fРасходМатериала;
        
        // *** Start programmer edit section *** (Трудозатраты CustomMembers)

        // *** End programmer edit section *** (Трудозатраты CustomMembers)

        
        /// <summary>
        /// ДатаОтчета.
        /// </summary>
        // *** Start programmer edit section *** (Трудозатраты.ДатаОтчета CustomAttributes)

        // *** End programmer edit section *** (Трудозатраты.ДатаОтчета CustomAttributes)
        public virtual System.DateTime ДатаОтчета
        {
            get
            {
                // *** Start programmer edit section *** (Трудозатраты.ДатаОтчета Get start)

                // *** End programmer edit section *** (Трудозатраты.ДатаОтчета Get start)
                System.DateTime result = this.fДатаОтчета;
                // *** Start programmer edit section *** (Трудозатраты.ДатаОтчета Get end)

                // *** End programmer edit section *** (Трудозатраты.ДатаОтчета Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Трудозатраты.ДатаОтчета Set start)

                // *** End programmer edit section *** (Трудозатраты.ДатаОтчета Set start)
                this.fДатаОтчета = value;
                // *** Start programmer edit section *** (Трудозатраты.ДатаОтчета Set end)

                // *** End programmer edit section *** (Трудозатраты.ДатаОтчета Set end)
            }
        }
        
        /// <summary>
        /// Трудозатраты.
        /// </summary>
        // *** Start programmer edit section *** (Трудозатраты.Сотрудники CustomAttributes)

        // *** End programmer edit section *** (Трудозатраты.Сотрудники CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудники"})]
        [NotNull()]
        public virtual IIS.Fotokiosk1.Сотрудники Сотрудники
        {
            get
            {
                // *** Start programmer edit section *** (Трудозатраты.Сотрудники Get start)

                // *** End programmer edit section *** (Трудозатраты.Сотрудники Get start)
                IIS.Fotokiosk1.Сотрудники result = this.fСотрудники;
                // *** Start programmer edit section *** (Трудозатраты.Сотрудники Get end)

                // *** End programmer edit section *** (Трудозатраты.Сотрудники Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Трудозатраты.Сотрудники Set start)

                // *** End programmer edit section *** (Трудозатраты.Сотрудники Set start)
                this.fСотрудники = value;
                // *** Start programmer edit section *** (Трудозатраты.Сотрудники Set end)

                // *** End programmer edit section *** (Трудозатраты.Сотрудники Set end)
            }
        }
        
        /// <summary>
        /// Трудозатраты.
        /// </summary>
        // *** Start programmer edit section *** (Трудозатраты.РасходМатериала CustomAttributes)

        // *** End programmer edit section *** (Трудозатраты.РасходМатериала CustomAttributes)
        public virtual IIS.Fotokiosk1.DetailArrayOfРасходМатериала РасходМатериала
        {
            get
            {
                // *** Start programmer edit section *** (Трудозатраты.РасходМатериала Get start)

                // *** End programmer edit section *** (Трудозатраты.РасходМатериала Get start)
                if ((this.fРасходМатериала == null))
                {
                    this.fРасходМатериала = new IIS.Fotokiosk1.DetailArrayOfРасходМатериала(this);
                }
                IIS.Fotokiosk1.DetailArrayOfРасходМатериала result = this.fРасходМатериала;
                // *** Start programmer edit section *** (Трудозатраты.РасходМатериала Get end)

                // *** End programmer edit section *** (Трудозатраты.РасходМатериала Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Трудозатраты.РасходМатериала Set start)

                // *** End programmer edit section *** (Трудозатраты.РасходМатериала Set start)
                this.fРасходМатериала = value;
                // *** Start programmer edit section *** (Трудозатраты.РасходМатериала Set end)

                // *** End programmer edit section *** (Трудозатраты.РасходМатериала Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТрудозатратыE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТрудозатратыE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТрудозатратыE", typeof(IIS.Fotokiosk1.Трудозатраты));
                }
            }
            
            /// <summary>
            /// "ТрудозатратыL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТрудозатратыL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТрудозатратыL", typeof(IIS.Fotokiosk1.Трудозатраты));
                }
            }
        }
    }
}
