//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Fotokiosk1
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Услуга.
    /// </summary>
    // *** Start programmer edit section *** (Услуга CustomAttributes)

    // *** End programmer edit section *** (Услуга CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("УслугаE", new string[] {
            "ДатаУслуги as \'Дата услуги\'",
            "Прайс as \'Прайс\'",
            "Прайс.Наименование as \'Наименование\'",
            "Прайс.Цена as \'Цена\'",
            "ЗаписьВремя as \'Запись время\'",
            "ЗаписьВремя.Время as \'Время\'"}, Hidden=new string[] {
            "Прайс.Наименование",
            "ЗаписьВремя.Время"})]
    [MasterViewDefineAttribute("УслугаE", "Прайс", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [MasterViewDefineAttribute("УслугаE", "ЗаписьВремя", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Время")]
    public class Услуга : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДатаУслуги;
        
        private IIS.Fotokiosk1.Прайс fПрайс;
        
        private IIS.Fotokiosk1.ЗаписьВремя fЗаписьВремя;
        
        private IIS.Fotokiosk1.ЗаписьКлиента fЗаписьКлиента;
        
        // *** Start programmer edit section *** (Услуга CustomMembers)

        // *** End programmer edit section *** (Услуга CustomMembers)

        
        /// <summary>
        /// ДатаУслуги.
        /// </summary>
        // *** Start programmer edit section *** (Услуга.ДатаУслуги CustomAttributes)

        // *** End programmer edit section *** (Услуга.ДатаУслуги CustomAttributes)
        public virtual System.DateTime ДатаУслуги
        {
            get
            {
                // *** Start programmer edit section *** (Услуга.ДатаУслуги Get start)

                // *** End programmer edit section *** (Услуга.ДатаУслуги Get start)
                System.DateTime result = this.fДатаУслуги;
                // *** Start programmer edit section *** (Услуга.ДатаУслуги Get end)

                // *** End programmer edit section *** (Услуга.ДатаУслуги Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Услуга.ДатаУслуги Set start)

                // *** End programmer edit section *** (Услуга.ДатаУслуги Set start)
                this.fДатаУслуги = value;
                // *** Start programmer edit section *** (Услуга.ДатаУслуги Set end)

                // *** End programmer edit section *** (Услуга.ДатаУслуги Set end)
            }
        }
        
        /// <summary>
        /// Услуга.
        /// </summary>
        // *** Start programmer edit section *** (Услуга.ЗаписьВремя CustomAttributes)

        // *** End programmer edit section *** (Услуга.ЗаписьВремя CustomAttributes)
        [PropertyStorage(new string[] {
                "ЗаписьВремя"})]
        [NotNull()]
        public virtual IIS.Fotokiosk1.ЗаписьВремя ЗаписьВремя
        {
            get
            {
                // *** Start programmer edit section *** (Услуга.ЗаписьВремя Get start)

                // *** End programmer edit section *** (Услуга.ЗаписьВремя Get start)
                IIS.Fotokiosk1.ЗаписьВремя result = this.fЗаписьВремя;
                // *** Start programmer edit section *** (Услуга.ЗаписьВремя Get end)

                // *** End programmer edit section *** (Услуга.ЗаписьВремя Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Услуга.ЗаписьВремя Set start)

                // *** End programmer edit section *** (Услуга.ЗаписьВремя Set start)
                this.fЗаписьВремя = value;
                // *** Start programmer edit section *** (Услуга.ЗаписьВремя Set end)

                // *** End programmer edit section *** (Услуга.ЗаписьВремя Set end)
            }
        }
        
        /// <summary>
        /// Услуга.
        /// </summary>
        // *** Start programmer edit section *** (Услуга.Прайс CustomAttributes)

        // *** End programmer edit section *** (Услуга.Прайс CustomAttributes)
        [PropertyStorage(new string[] {
                "Прайс"})]
        [NotNull()]
        public virtual IIS.Fotokiosk1.Прайс Прайс
        {
            get
            {
                // *** Start programmer edit section *** (Услуга.Прайс Get start)

                // *** End programmer edit section *** (Услуга.Прайс Get start)
                IIS.Fotokiosk1.Прайс result = this.fПрайс;
                // *** Start programmer edit section *** (Услуга.Прайс Get end)

                // *** End programmer edit section *** (Услуга.Прайс Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Услуга.Прайс Set start)

                // *** End programmer edit section *** (Услуга.Прайс Set start)
                this.fПрайс = value;
                // *** Start programmer edit section *** (Услуга.Прайс Set end)

                // *** End programmer edit section *** (Услуга.Прайс Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Fotokiosk1.ЗаписьКлиента.
        /// </summary>
        // *** Start programmer edit section *** (Услуга.ЗаписьКлиента CustomAttributes)

        // *** End programmer edit section *** (Услуга.ЗаписьКлиента CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "ЗаписьКлиента"})]
        public virtual IIS.Fotokiosk1.ЗаписьКлиента ЗаписьКлиента
        {
            get
            {
                // *** Start programmer edit section *** (Услуга.ЗаписьКлиента Get start)

                // *** End programmer edit section *** (Услуга.ЗаписьКлиента Get start)
                IIS.Fotokiosk1.ЗаписьКлиента result = this.fЗаписьКлиента;
                // *** Start programmer edit section *** (Услуга.ЗаписьКлиента Get end)

                // *** End programmer edit section *** (Услуга.ЗаписьКлиента Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Услуга.ЗаписьКлиента Set start)

                // *** End programmer edit section *** (Услуга.ЗаписьКлиента Set start)
                this.fЗаписьКлиента = value;
                // *** Start programmer edit section *** (Услуга.ЗаписьКлиента Set end)

                // *** End programmer edit section *** (Услуга.ЗаписьКлиента Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "УслугаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View УслугаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("УслугаE", typeof(IIS.Fotokiosk1.Услуга));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Услуга.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfУслуга CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfУслуга CustomAttributes)
    public class DetailArrayOfУслуга : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Fotokiosk1.DetailArrayOfУслуга members)

        // *** End programmer edit section *** (IIS.Fotokiosk1.DetailArrayOfУслуга members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Услуга by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Услуга.
        /// </summary>
        public DetailArrayOfУслуга(IIS.Fotokiosk1.ЗаписьКлиента fЗаписьКлиента) : 
                base(typeof(Услуга), ((ICSSoft.STORMNET.DataObject)(fЗаписьКлиента)))
        {
        }
        
        public IIS.Fotokiosk1.Услуга this[int index]
        {
            get
            {
                return ((IIS.Fotokiosk1.Услуга)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Fotokiosk1.Услуга dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
